// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

type Comments struct {
	CreatedAt   time.Time  `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP;NOT NULL" json:"-"`
	UpdatedAt   time.Time  `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP;NOT NULL" json:"-"`
	DeletedAt   *time.Time `gorm:"column:deleted_at;type:datetime" json:"-"`
	Cid         uint       `gorm:"column:cid;type:int(11) unsigned;primary_key;AUTO_INCREMENT" json:"cid"`
	Product     uint       `gorm:"column:product;type:int(11) unsigned;NOT NULL" json:"product"`
	Commentator uint       `gorm:"column:commentator;type:int(11) unsigned;NOT NULL" json:"commentator"`
	ResponseTo  *uint      `gorm:"column:response_to;type:int(11) unsigned" json:"response_to"`
	Text        *string    `gorm:"column:text;type:longtext" json:"text"`
}

type Images struct {
	CreatedAt time.Time  `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP;NOT NULL" json:"-"`
	UpdatedAt time.Time  `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP;NOT NULL" json:"-"`
	DeletedAt *time.Time `gorm:"column:deleted_at;type:datetime" json:"-"`
	Iid       uint       `gorm:"column:iid;type:int(11) unsigned;AUTO_INCREMENT;NOT NULL" json:"iid"`
	Address   string     `gorm:"column:address;type:text;NOT NULL" json:"address"`
	Products  uint       `gorm:"column:products;type:int(11) unsigned;NOT NULL" json:"products"`
}

type Messages struct {
	CreatedAt time.Time  `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP;NOT NULL" json:"-"`
	UpdatedAt time.Time  `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP;NOT NULL" json:"-"`
	DeletedAt *time.Time `gorm:"column:deleted_at;type:datetime" json:"-"`
	Mid       uint       `gorm:"column:mid;type:int(11) unsigned;primary_key;AUTO_INCREMENT" json:"mid"`
	From      uint       `gorm:"column:from;type:int(11) unsigned;NOT NULL" json:"from"`
	To        uint       `gorm:"column:to;type:int(11) unsigned;NOT NULL" json:"to"`
	Text      *string    `gorm:"column:text;type:varchar(255)" json:"text"`
}

type Products struct {
	CreatedAt time.Time  `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP;NOT NULL" json:"-"`
	UpdatedAt time.Time  `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP;NOT NULL" json:"-"`
	DeletedAt *time.Time `gorm:"column:deleted_at;type:datetime" json:"-"`
	Pid       uint       `gorm:"column:pid;type:int(11) unsigned;primary_key;AUTO_INCREMENT" json:"pid"`
	Title     string     `gorm:"column:title;type:varchar(63);NOT NULL" json:"title"`
	Info      *string    `gorm:"column:info;type:text" json:"info"`
	Price     string     `gorm:"column:price;type:decimal(6,2);NOT NULL" json:"price"`
	Owner     uint       `gorm:"column:owner;type:int(11) unsigned;NOT NULL" json:"owner"`
	Location  *string    `gorm:"column:location;type:varchar(255)" json:"location"`
}

type Users struct {
	CreatedAt time.Time  `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP;NOT NULL" json:"-"`
	UpdatedAt time.Time  `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP;NOT NULL" json:"-"`
	DeletedAt *time.Time `gorm:"column:deleted_at;type:datetime" json:"-"`
	Uid       uint       `gorm:"column:uid;type:int(11) unsigned;primary_key;AUTO_INCREMENT" json:"uid"`
	Username  string     `gorm:"column:username;type:varchar(32);NOT NULL" json:"username"`
	Email     string     `gorm:"column:email;type:varchar(255);NOT NULL" json:"email"`
	Hashed    string     `gorm:"column:hashed;type:char(64);NOT NULL" json:"-"`     // 密码哈希
	Avatar    string     `gorm:"column:avatar;type:varchar(255)" json:"avatar"`     // 头像
	Info      string     `gorm:"column:info;type:varchar(255)" json:"info"`         // 简历
	Profile   string     `gorm:"column:profile;type:text" json:"profile"`           // 详历
	Location  string     `gorm:"column:location;type:varchar(255)" json:"location"` // 默认地址
}
